### ISSUE TITLE
Still getting 7.9 compatibility issue warnings

### ISSUE THREAD

**Issue by olytron** [Handyfon/roll-of-fate#11]
Hello!

The documents says the module is 8.x compatible but I am getting a compatibility issue warning. I am running Foundry 8.8

**Comment by Faeranne** [comment]
Looks like the manifest file still points to an old zip file.
I hand installed the fateroll.zip file, and removed the manifest.json line pointing to the original manifest, and it seems to work fine.

**Comment by olytron** [comment]
> Looks like the manifest file still points to an old zip file.
> I hand installed the fateroll.zip file, and removed the manifest and download lines pointing to the original manifest and zip, and it seems to work fine.

That worked on my local copy, but I don't have access to the module folders where I am using a hosting service. Oh well, let's hope the link will be fixed one day. Thanks for your help
