### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/roll-of-fate#14]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by rmasoni** [comment]
It's actually declared as `"compatibleCoreVersion": "0.8.9"`, but as it's working fine on v9, a version bump would probably suffice.
