### ISSUE TITLE
Problems with color text (Conflict with Chat Portrait module)

### ISSUE THREAD

**Issue by Fridan99** [Handyfon/roll-of-fate#15]
**Describe the bug**
Apparently there is an interaction between the roll of fate and the chat portrait. When used together, the roll of fate letters cannot change color. 

I am not sure which module creates the actual conflict, chat portrait or roll of fate. 

**To Reproduce**
1. Go to 'install Roll of Fate and Chat Portrait modules'

**Expected behavior**
No conflict with modules. 

**Screenshots**
![text](https://user-images.githubusercontent.com/86131373/153010827-d6335e6c-cb4d-44c6-8b21-8073376db51c.jpg)

**Browser:**
 NO. App itself

**Foundry 0.9.249**
**System dnd5e 1.5.7**
**Roll of Fate 0.4.6**
**Chat Portrait 0.6.0**

**Comment by p4535992** [comment]
@Handyfon For fix this the right way on my side i need you to add some customize class on the html of the chat message like `roll-of-fate` the most simple example:

`<div class="roll-of-fate" style="background: ${sBackgroundColor};`

**Comment by Handyfon** [comment]
Unfortunatly it isn't as simple as a fix a chat potraits just inserts its custom classes into the roll of fate cards, even when all references to base foundry classes are removed. I included a fix that overwrites the color and center but it's not as customizable except for custom css.

**Comment by p4535992** [comment]
hello sorry maybe I expressed myself wrong what I mean is that for my use case _I need any html element that allows me to identify the message as coming from your module_ (at the level of pure html content I mean). It could also be an attribute like `data-roll-of-fate=true` .
