### ISSUE TITLE
I can't add a space to the start of Suffix

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/roll-of-fate#2]
Hi. Nice module!

I can't add a space to the start of suffix.
![image](https://user-images.githubusercontent.com/4999783/99075994-2b343d80-2599-11eb-85b8-d072b05b6c09.png)

After save it's removed.
![image](https://user-images.githubusercontent.com/4999783/99076022-3d15e080-2599-11eb-8176-80fbdd4d699a.png)

**Comment by pete284** [comment]
If you use the html syntax &nbsp; it will work
example: &nbsp;you have been chosen

**Comment by Handyfon** [comment]
Issues like this should be fixed with the 0.4 release
