### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by weepingminotaur** [Handyfon/roll-of-fate#22]
Just a request for v11 compatibility. Love this module!

**Comment by Fridan99** [comment]
I second the motion

**Comment by Txus5012** [comment]
The module works perfectly in v11 as it is.

**Comment by Fridan99** [comment]
So it's just a versioning problem

**Comment by warhammering** [comment]
This module is not working as intended. The role still work but I am getting this in my cards. The formatting is gone

![image](https://github.com/Handyfon/roll-of-fate/assets/140810683/b535fb8b-df25-4567-a500-ca53b67f0bf4)
So is coming out like this

**Comment by warhammering** [comment]
I get this error message in the console
![image](https://github.com/Handyfon/roll-of-fate/assets/140810683/6d850b14-e9ce-41da-8c42-5b3bd0298ae3)

**Comment by Txus5012** [comment]
Works well here (also in WFRP4e):
![Roll of Fate](https://github.com/Handyfon/roll-of-fate/assets/87753744/81771d68-ce39-433e-8744-5839d57cb5de)

That is a deprecation warning. It will stop working in v12, you can ignore it in v11.

**Comment by weepingminotaur** [comment]
Bumping up a request for v11 compatibility. I know it works, but the constant yellow warnings upon login are annoying.
