### ISSUE TITLE
Feature request: chat card appearance

### ISSUE THREAD

**Issue by NutritiousCookie** [Handyfon/roll-of-fate#3]
- The title is like 5x the font size of the actual content of the message. It should be the same size.
- Leaving the title blank still generates lines where the title would go. If the title is blank, these should be disabled.
- Glow effect on the text should be able to be disabled.

![Screenshot 2020-11-16 125530](https://user-images.githubusercontent.com/30578022/99295453-0d6e0f00-280b-11eb-80e9-5a452525eee6.png)
![Screenshot 2020-11-16 125454](https://user-images.githubusercontent.com/30578022/99295456-0e06a580-280b-11eb-95ba-bc1fae7fc3a4.png)

**Comment by Handyfon** [comment]
Included functionality in ROF 0.4
