### ISSUE TITLE
All Options displaying in output

### ISSUE THREAD

**Issue by pete284** [Handyfon/roll-of-fate#5]
Running Roll of Fate in two separate worlds both using the 5e system. In one world it works correctly in the other it is displaying all the option in the output (see attached screenshots). There are no errors in the console I have tried the following options:
- Complete re-install of the module
- deleted all entries and run
- tried separating choices by comma
- separating choices by more than one line

![ROF Config](https://user-images.githubusercontent.com/55640052/105579866-04f10200-5d81-11eb-97ef-5cc93c457c78.png)
![ROF Output](https://user-images.githubusercontent.com/55640052/105579868-09b5b600-5d81-11eb-822d-cfa36d23c60c.png)

Is there a config file I can delete that is hiding somewhere holding the settings

**Comment by Handyfon** [comment]
fixed with the new update
