### ISSUE TITLE
Module update loops due to invalid version

### ISSUE THREAD

**Issue by zarmstrong** [Handyfon/roll-of-fate#9]
Can you increment version to 0.4.6 instead of 0.4.5.1, as foundry doesn't read the 4th #

**Comment by jailtondamasceno** [comment]
Same problem here!

**Comment by Luisphigor** [comment]
Confirm the issue, please fix. thanks

**Comment by jailtondamasceno** [comment]
Still looping on version 0.4.5 for me.

**Comment by zarmstrong** [comment]
Not seeing any code change/fix pushed.  Still broken
